import React, { useState, useContext } from 'react'
import GenericCreator from '../generic-creator-components/GenericCreator'
import GarmentContext from '../../context'
import { garmentProfiles } from '../../utility/sample-data'

const TopCreator = function TopCreator(): JSX.Element {
    const {
        top,
        setTop,
        top2,
        setTop2,
        top3,
        setTop3,
        sleeves,
        setSleeves,
        sleeves2,
        setSleeves2,
        sleeves3,
        setSleeves3,
        collar,
        setCollar,
        collar2,
        setCollar2,
        collar3,
        setCollar3,
    } = useContext(GarmentContext)
    const [savedTops, setSavedTops] = useState([])
    return (
        <GenericCreator
            tabItems={[
                {
                    label: 'Bodice First',
                    cssClasses: 'set1 set-start',
                    item: top,
                    itemSetter: setTop,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.tops,
                    // garmentData: garmentProfiles.tops.skinTight,
                    required: true,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Collar One',
                    cssClasses: 'set1 set-middle',
                    item: collar,
                    itemSetter: setCollar,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.collars,
                    // garmentData: garmentProfiles.collars.skinTight,
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Sleeves One',
                    cssClasses: 'set1 set-end',
                    item: sleeves,
                    itemSetter: setSleeves,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.sleeves,
                    // garmentData: garmentProfiles.sleeves['Puff Sleeves'],
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Bodice Second',
                    cssClasses: 'set2 set-start',
                    item: top2,
                    itemSetter: setTop2,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.tops,
                    // garmentData: garmentProfiles.tops.skinTight,
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Collar Two',
                    cssClasses: 'set2 set-middle',
                    item: collar2,
                    itemSetter: setCollar2,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.collars,
                    // garmentData: garmentProfiles.collars.skinTight,
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Sleeves Two',
                    cssClasses: 'set2 set-end',
                    item: sleeves2,
                    itemSetter: setSleeves2,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.sleeves,
                    // garmentData: garmentProfiles.sleeves['Puff Sleeves'],
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Bodice Third',
                    cssClasses: 'set3 set-start',
                    item: top3,
                    itemSetter: setTop3,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.tops,
                    // garmentData: garmentProfiles.tops.skinTight,
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Collar Three',
                    cssClasses: 'set3 set-middle',
                    item: collar3,
                    itemSetter: setCollar3,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.collars,
                    // garmentData: garmentProfiles.collars.skinTight,
                    required: false,
                    previewClass: 'preview-top',
                },
                {
                    label: 'Sleeves Three',
                    cssClasses: 'set3 set-end',
                    item: sleeves3,
                    itemSetter: setSleeves3,
                    savedItems: savedTops,
                    setSavedItems: setSavedTops,
                    data: garmentProfiles.sleeves,
                    // garmentData: garmentProfiles.sleeves['Puff Sleeves'],
                    required: false,
                    previewClass: 'preview-top',
                },
            ]}
        />
    )
}
export default TopCreator
